const { Router } = require('express');
const authRoutes = require('./auth.routes');
const usersRoutes = require('./users.routes');
const rolesRoutes = require('./roles.routes');
const permissionsRoutes = require('./permissions.routes');
const companiesRoutes = require('./companies.routes');
const capabilitiesRoutes = require('./capabilities.routes');
const profileRoutes = require('./profile.routes');
const addressesRoutes = require('./addresses.routes');
const contactsRoutes = require('./contacts.routes');
const odooConnectionsRoutes = require('./odooConnections.routes');
const auditLogsRoutes = require('./auditLogs.routes');
const dashboardRoutes = require('./dashboard.routes');
const quotationsRoutes = require('./quotations.routes');
const ordersRoutes = require('./orders.routes');
const invoicesRoutes = require('./invoices.routes');
const deliveriesRoutes = require('./deliveries.routes');
const requestsRoutes = require('./requests.routes');
const documentsRoutes = require('./documents.routes');
const notificationsRoutes = require('./notifications.routes');
const productsRoutes = require('./products.routes');
const ticketsRoutes = require('./tickets.routes');
const rmaRoutes = require('./rma.routes');
const warrantyRoutes = require('./warranty.routes');
const maintenanceRoutes = require('./maintenance.routes');
const equipmentRoutes = require('./equipment.routes');
const subscriptionsRoutes = require('./subscriptions.routes');
const analyticsRoutes = require('./analytics.routes');
const odooWebhooksRoutes = require('./odooWebhooks.routes');
const assistantRoutes = require('./assistant.routes');
const adminAssistantRoutes = require('./adminAssistant.routes');

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/roles', rolesRoutes);
router.use('/permissions', permissionsRoutes);
router.use('/companies', companiesRoutes);
router.use('/capabilities', capabilitiesRoutes);
router.use('/profile', profileRoutes);
router.use('/addresses', addressesRoutes);
router.use('/contacts', contactsRoutes);
router.use('/admin/odoo-connections', odooConnectionsRoutes);
router.use('/audit-logs', auditLogsRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/quotations', quotationsRoutes);
router.use('/orders', ordersRoutes);
router.use('/invoices', invoicesRoutes);
router.use('/deliveries', deliveriesRoutes);
router.use('/requests', requestsRoutes);
router.use('/documents', documentsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/products', productsRoutes);
router.use('/tickets', ticketsRoutes);
router.use('/rma', rmaRoutes);
router.use('/warranty', warrantyRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/equipment', equipmentRoutes);
router.use('/subscriptions', subscriptionsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/webhooks/odoo', odooWebhooksRoutes);
router.use('/assistant', assistantRoutes);
router.use('/admin/assistant', adminAssistantRoutes);

module.exports = router;
